
### Used VLANs will be decided (VLAN 10-20 or VLAN 11, 12, 21, 22, 31, 32)
# ---
# port_profiles:
#   - profile: pod1_servers
#     mode: trunk
#     vlans: 11,12
#   - profile: pod2_servers
#     mode: trunk
#     vlans: 21,22
#   - profile: pod3_servers
#     mode: trunk
#     vlans: 31,32

---
port_profiles:
  - profile: Pod1_Host-A
    mode: trunk
    vlans: '11'
  - profile: Pod1_Host-B
    mode: trunk
    vlans: '12'
  - profile: Pod2_Host-C
    mode: trunk
    vlans: '21'
  - profile: Pod2_Host-D
    mode: trunk
    vlans: '22'
  - profile: Pod3_Host-E
    mode: trunk
    vlans: '31'
  - profile: Pod3_Host-F
    mode: trunk
    vlans: '32'

# Definition of connected endpoints in the fabric.
servers:
  - name: Host-A
    adapters:
        # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [Ethernet1, Ethernet2]
        # Switch interfaces where the server ports are connected.
        switch_ports: [Ethernet5, Ethernet5]
        # Switch names where the server ports are connected.
        switches: [Leaf1, Leaf2]
        # VLANs that will be configured on these ports.
        profile: Pod1_Host-A
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        port_channel:
          description: MLAG_PortChannel
          mode: active
  - name: Host-B
    adapters:
        # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [Ethernet1, Ethernet2]
        # Switch interfaces where the server ports are connected.
        switch_ports: [Ethernet6, Ethernet6]
        # Switch names where the server ports are connected.
        switches: [Leaf1, Leaf2]
        # VLANs that will be configured on these ports.
        profile: Pod1_Host-B
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        port_channel:
          description: MLAG_PortChannel
          mode: active
  - name: Host-C
    adapters:
        # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [Ethernet1, Ethernet2]
        # Switch interfaces where the server ports are connected.
        switch_ports: [Ethernet5, Ethernet5]
        # Switch names where the server ports are connected.
        switches: [Leaf3, Leaf4]
        # VLANs that will be configured on these ports.
        profile: Pod2_Host-C
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        port_channel:
          description: MLAG_PortChannel
          mode: active
  - name: Host-D
    adapters:
        # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [Ethernet1, Ethernet2]
        # Switch interfaces where the server ports are connected.
        switch_ports: [Ethernet6, Ethernet6]
        # Switch names where the server ports are connected.
        switches: [Leaf3, Leaf4]
        # VLANs that will be configured on these ports.
        profile: Pod2_Host-D
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        port_channel:
          description: MLAG_PortChannel
          mode: active
  - name: Host-E
    adapters:
        # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [Ethernet1, Ethernet2]
        # Switch interfaces where the server ports are connected.
        switch_ports: [Ethernet5, Ethernet5]
        # Switch names where the server ports are connected.
        switches: [Leaf5, Leaf6]
        # VLANs that will be configured on these ports.
        profile: Pod3_Host-E
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        port_channel:
          description: EVPN_AA_PortChannel
          mode: active
        ethernet_segment:
          short_esi: "0000:0000:0001"
  - name: Host-F
    adapters:
        # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [Ethernet1, Ethernet2]
        # Switch interfaces where the server ports are connected.
        switch_ports: [Ethernet6, Ethernet6]
        # Switch names where the server ports are connected.
        switches: [Leaf5, Leaf6]
        # VLANs that will be configured on these ports.
        profile: Pod3_Host-F
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        port_channel:
          description: EVPN_AA_PortChannel
          mode: active
        ethernet_segment:
          short_esi: "0000:0000:0002"
