# EOS connection vars
ansible_user: admin
ansible_password: admin
ansible_network_os: eos
ansible_connection: httpapi
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_httpapi_port: 443
ansible_become: true
ansible_become_method: enable